spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastrousuarios
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update





